mysql:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: asdasd
        MYSQL_DATABASE: scraper
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_RANDOM_ROOT_PASSWORD: "no"
        MYSQL_USER: lukas
        MYSQL_PASSWORD: lukas

rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"